version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    # image: markeybass/census-surveyor-client:latest
    image: ${DOCKERHUB_USERNAME}/census-surveyor-client:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://server:8000/api/v1
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # image: markeybass/census-surveyor-server:latest
    image: ${DOCKERHUB_USERNAME}/census-surveyor-server:${TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://mark_k:TaboSpiti2008@nodemongoproject1.3n1rv.mongodb.net/census-surveyor?retryWrites=true&w=majority&appName=NodeMongoProject1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_USER_PROFILE_PHOTO_UPLOAD_PATH=${S3_USER_PROFILE_PHOTO_UPLOAD_PATH}
      - MAX_FILE_SIZE_TO_UPLOAD=${MAX_FILE_SIZE_TO_UPLOAD}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb_data: 