services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    # image: markeybass/census-surveyor-client:latest
    # image: ${DOCKERHUB_USERNAME}/census-surveyor-client:${TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # - NEXT_PUBLIC_API_URL=http://server:8000/api/v1
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # image: markeybass/census-surveyor-server:latest
    # image: ${DOCKERHUB_USERNAME}/census-surveyor-server:${TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT:-8000}
      - NODE_ENV=${NODE_ENV:-development}
      - CLIENT_URL=${CLIENT_URL}
      - MAX_FILE_SIZE_TO_UPLOAD=${MAX_FILE_SIZE_TO_UPLOAD}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_USER_PROFILE_PHOTO_UPLOAD_PATH=${S3_USER_PROFILE_PHOTO_UPLOAD_PATH}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb_data: 