name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: app.markeybass.net
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/census-surveyor-app || mkdir -p /home/ubuntu/census-surveyor-app
            cd /home/ubuntu/census-surveyor-app
            git clone https://github.com/${{ github.repository }}.git . || git pull origin main
            
            # Create .env file
            cat > .env << EOL
            NODE_ENV=production
            PORT=8000
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            MAX_FILE_SIZE_TO_UPLOAD=${{ secrets.MAX_FILE_SIZE_TO_UPLOAD }}
            CLIENT_URL=${{ secrets.CLIENT_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            S3_REGION=${{ secrets.S3_REGION }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            S3_USER_PROFILE_PHOTO_UPLOAD_PATH=${{ secrets.S3_USER_PROFILE_PHOTO_UPLOAD_PATH }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            EOL

            # Stop and remove existing containers
            docker-compose down -v || true
            
            # Clean up unused Docker resources
            docker system prune -f || true
            
            # Build and start containers
            docker-compose up -d --build || {
              echo "Failed to start containers"
              docker-compose logs
              exit 1
            }
